#!/bin/bash
# Script 5: Open Source Manifesto Generator (Linux Kernel)

echo "Answer three questions to generate your manifesto."
echo ""

read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# Compose manifesto paragraph
echo "On $DATE, I reflect on the power of open source through the lens of the Linux Kernel. Using tools like $TOOL, I experience the true meaning of $FREEDOM in computing. The Linux Kernel represents a world where collaboration, transparency, and innovation thrive without restrictions. Inspired by this philosophy, I aspire to build and freely share $BUILD with the global community. I believe that open source is not just about code, but about empowering people to learn, create, and contribute without barriers." > "$OUTPUT"

# Append a closing line
echo "" >> "$OUTPUT"
echo "— Generated by $(whoami) on a Linux system" >> "$OUTPUT"

echo ""
echo "Manifesto saved to $OUTPUT"
echo "--------------------------------------"
cat "$OUTPUT"